"""
Django settings for portfolio project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-1^2&adwg10fsb+d(y2&dnj=p%6-zpn4zw(u-)*ybcky)21b595'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

 


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'portf',
    'social_django',
    'django.contrib.sites',
]
SITE_ID = 1
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    
]

ROOT_URLCONF = 'portfolio.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
    'django.template.context_processors.request',

    'django.contrib.auth.context_processors.auth',
    'django.contrib.messages.context_processors.messages',

    'social_django.context_processors.backends',
    'social_django.context_processors.login_redirect',
],
        },
    },
]

WSGI_APPLICATION = 'portfolio.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'



AUTHENTICATION_BACKENDS = (
    'social_core.backends.google.GoogleOAuth2',
    'social_core.backends.github.GithubOAuth2',
    #'social_core.backends.facebook.FacebookOAuth2',

    'django.contrib.auth.backends.ModelBackend',
)
import os
SOCIAL_AUTH_GITHUB_KEY = os.environ.get(
    'SOCIAL_AUTH_GITHUB_KEY'
)

SOCIAL_AUTH_GITHUB_SECRET = os.environ.get(
    'SOCIAL_AUTH_GITHUB_SECRET'
)

#SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = '457719391438-cckm4u65sbt47fts98ptge5ftlfd3usb.apps.googleusercontent.com'
#SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = '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'

#SOCIAL_AUTH_GITHUB_KEY = 'Ov23lisZC5FFJqzK2rXN'
#SOCIAL_AUTH_GITHUB_SECRET = 'cb270642c0fb0135a02f271cc748136fd6e1ddfd'








# GOOGLE
SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = os.environ.get(
   'SOCIAL_AUTH_GOOGLE_OAUTH2_KEY'

)

SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = os.environ.get(
    'SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET'
)


LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'


MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

ALLOWED_HOSTS = ['portfolio-2ews.onrender.com', '127.0.0.1','localhost']


SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

SOCIAL_AUTH_REDIRECT_IS_HTTPS = True

SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True

#SESSION_COOKIE_SAMESITE = 'Lax'
#CSRF_COOKIE_SAMESITE = 'Lax'

CSRF_TRUSTED_ORIGINS = [
    'https://portfolio-2ews.onrender.com',

    'http://127.0.0.1:8000',
    'http://localhost:8000',
]


SOCIAL_AUTH_REDIRECT_IS_HTTPS = True